students_get_average:
  path: '/api/students/{id}/avg'
  methods:  ['GET']
  defaults:
    _controller: 'App\Controller\StudentMarkAverage::average'
    _api_resource_class: 'App\Entity\Student'
    _api_item_operation_name: 'average'
